/**
 * Generates server/data/schemes.xlsx with 18 real Indian government schemes.
 * Run: node scripts/generate-schemes.js
 */
const XLSX = require(require.resolve('xlsx', { paths: [require('path').join(__dirname, '../server/node_modules')] }));
const path = require('path');

const schemes = [
  {
    id: 1,
    name: 'PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)',
    description: 'Direct income support of Rs 6,000 per year to small and marginal farmers with landholding up to 2 hectares, paid in three installments of Rs 2,000.',
    category: 'Agriculture',
    state: 'National',
    eligibility_age_min: 18,
    eligibility_age_max: 999,
    eligibility_income_max: 99999999,
    eligibility_gender: 'Any',
    eligibility_caste: 'Any',
    apply_url: 'https://pmkisan.gov.in/',
    documents_required: 'Aadhaar Card, Bank Account Details, Land Records',
    benefits: 'Rs 6,000 per year direct bank transfer in 3 installments of Rs 2,000 each',
    language: 'English, Hindi, Telugu',
  },
  {
    id: 2,
    name: 'Ayushman Bharat PM-JAY',
    description: 'Health insurance coverage of Rs 5 lakh per family per year for secondary and tertiary hospitalization. Covers 50 crore beneficiaries from poor and vulnerable families.',
    category: 'Health',
    state: 'National',
    eligibility_age_min: 0,
    eligibility_age_max: 999,
    eligibility_income_max: 100000,
    eligibility_gender: 'Any',
    eligibility_caste: 'Any',
    apply_url: 'https://pmjay.gov.in/',
    documents_required: 'Aadhaar Card, Ration Card, Income Certificate',
    benefits: 'Rs 5 lakh health cover per family per year, cashless treatment at empaneled hospitals',
    language: 'English, Hindi',
  },
  {
    id: 3,
    name: 'PM Awas Yojana - Urban (PMAY-U)',
    description: 'Housing for All initiative providing affordable housing to urban poor through interest subsidy on home loans. Target beneficiaries include EWS, LIG, and MIG categories.',
    category: 'Housing',
    state: 'National',
    eligibility_age_min: 18,
    eligibility_age_max: 999,
    eligibility_income_max: 1800000,
    eligibility_gender: 'Any',
    eligibility_caste: 'Any',
    apply_url: 'https://pmaymis.gov.in/',
    documents_required: 'Aadhaar Card, Income Certificate, Bank Account, Address Proof',
    benefits: 'Interest subsidy up to Rs 2.67 lakh on home loans for EWS/LIG; credit linked subsidy for MIG',
    language: 'English, Hindi',
  },
  {
    id: 4,
    name: 'PM Awas Yojana - Gramin (PMAY-G)',
    description: 'Provides financial assistance to rural poor for construction of pucca houses with basic amenities. Replaces Indira Awaas Yojana.',
    category: 'Housing',
    state: 'National',
    eligibility_age_min: 18,
    eligibility_age_max: 999,
    eligibility_income_max: 200000,
    eligibility_gender: 'Any',
    eligibility_caste: 'Any',
    apply_url: 'https://pmayg.nic.in/',
    documents_required: 'Aadhaar Card, BPL Certificate, Bank Account, MGNREGA Job Card',
    benefits: 'Rs 1.2 lakh (plains) or Rs 1.3 lakh (hilly areas) for house construction',
    language: 'English, Hindi',
  },
  {
    id: 5,
    name: 'Beti Bachao Beti Padhao',
    description: 'Initiative to address declining child sex ratio and promote girl child welfare. Focuses on preventing gender-biased sex selective elimination and ensuring education and participation of the girl child.',
    category: 'Women Empowerment',
    state: 'National',
    eligibility_age_min: 0,
    eligibility_age_max: 18,
    eligibility_income_max: 99999999,
    eligibility_gender: 'Female',
    eligibility_caste: 'Any',
    apply_url: 'https://wcd.nic.in/bbbp-schemes',
    documents_required: 'Birth Certificate, Aadhaar Card',
    benefits: 'Education support, awareness programs, scholarships for girl child',
    language: 'English, Hindi',
  },
  {
    id: 6,
    name: 'MGNREGA (Mahatma Gandhi National Rural Employment Guarantee)',
    description: 'Guarantees 100 days of wage employment per year to rural households whose adult members volunteer to do unskilled manual work.',
    category: 'Employment',
    state: 'National',
    eligibility_age_min: 18,
    eligibility_age_max: 999,
    eligibility_income_max: 99999999,
    eligibility_gender: 'Any',
    eligibility_caste: 'Any',
    apply_url: 'https://nrega.nic.in/',
    documents_required: 'Job Card, Aadhaar Card, Bank Account',
    benefits: '100 days guaranteed employment per year at minimum wage, unemployment allowance if work not provided',
    language: 'English, Hindi, Telugu',
  },
  {
    id: 7,
    name: 'PM Scholarship Scheme (PMSS)',
    description: 'Scholarship for wards of ex-servicemen and ex-coast guard personnel for professional degree courses. Promotes quality technical and professional education among dependents of defense personnel.',
    category: 'Education',
    state: 'National',
    eligibility_age_min: 17,
    eligibility_age_max: 25,
    eligibility_income_max: 99999999,
    eligibility_gender: 'Any',
    eligibility_caste: 'Any',
    apply_url: 'https://ksb.gov.in/',
    documents_required: 'Ex-serviceman Certificate, Aadhaar Card, Mark Sheets, Bank Account',
    benefits: 'Rs 2,500 per month for boys and Rs 3,000 per month for girls',
    language: 'English, Hindi',
  },
  {
    id: 8,
    name: 'Sukanya Samriddhi Yojana (SSY)',
    description: 'Small savings scheme for the girl child under Beti Bachao Beti Padhao campaign. Account can be opened in the name of a girl child below 10 years of age.',
    category: 'Women Empowerment',
    state: 'National',
    eligibility_age_min: 0,
    eligibility_age_max: 10,
    eligibility_income_max: 99999999,
    eligibility_gender: 'Female',
    eligibility_caste: 'Any',
    apply_url: 'https://www.india.gov.in/sukanya-samriddhi-yojna',
    documents_required: "Girl Child Birth Certificate, Guardian's Aadhaar, Address Proof",
    benefits: 'High interest rate (currently ~8%), tax benefits under Section 80C, maturity amount at age 21',
    language: 'English, Hindi',
  },
  {
    id: 9,
    name: 'Atal Pension Yojana (APY)',
    description: 'Pension scheme focused on unorganized sector workers. Subscribers receive a fixed pension of Rs 1,000 to Rs 5,000 per month after the age of 60.',
    category: 'Employment',
    state: 'National',
    eligibility_age_min: 18,
    eligibility_age_max: 40,
    eligibility_income_max: 99999999,
    eligibility_gender: 'Any',
    eligibility_caste: 'Any',
    apply_url: 'https://npscra.nsdl.co.in/apy.php',
    documents_required: 'Aadhaar Card, Savings Bank Account, Mobile Number',
    benefits: 'Guaranteed pension of Rs 1,000 to Rs 5,000 per month after age 60',
    language: 'English, Hindi',
  },
  {
    id: 10,
    name: 'Pradhan Mantri Mudra Yojana (PMMY)',
    description: 'Provides loans up to Rs 10 lakh to non-corporate, non-farm small/micro enterprises. Three categories: Shishu (up to Rs 50,000), Kishore (Rs 50,001 to Rs 5 lakh), and Tarun (Rs 5 lakh to Rs 10 lakh).',
    category: 'Employment',
    state: 'National',
    eligibility_age_min: 18,
    eligibility_age_max: 999,
    eligibility_income_max: 99999999,
    eligibility_gender: 'Any',
    eligibility_caste: 'Any',
    apply_url: 'https://www.mudra.org.in/',
    documents_required: 'Aadhaar Card, PAN Card, Business Plan, Bank Statements',
    benefits: 'Collateral-free loans up to Rs 10 lakh for small businesses and startups',
    language: 'English, Hindi',
  },
  {
    id: 11,
    name: 'National Scholarship Portal (NSP)',
    description: 'Single portal providing various scholarships from central and state governments for students from classes 1 to PhD level. Covers merit-cum-means scholarships, minority scholarships, and more.',
    category: 'Education',
    state: 'National',
    eligibility_age_min: 6,
    eligibility_age_max: 30,
    eligibility_income_max: 250000,
    eligibility_gender: 'Any',
    eligibility_caste: 'Any',
    apply_url: 'https://scholarships.gov.in/',
    documents_required: 'Aadhaar Card, Mark Sheets, Income Certificate, Bank Account, Caste Certificate',
    benefits: 'Various scholarships from Rs 1,000 to Rs 10,000 per month depending on level and category',
    language: 'English, Hindi, Telugu',
  },
  {
    id: 12,
    name: 'Kisan Credit Card (KCC)',
    description: 'Provides farmers with timely access to credit for agricultural and allied needs. Covers crop cultivation expenses, post-harvest expenses, and maintenance of farm assets.',
    category: 'Agriculture',
    state: 'National',
    eligibility_age_min: 18,
    eligibility_age_max: 999,
    eligibility_income_max: 99999999,
    eligibility_gender: 'Any',
    eligibility_caste: 'Any',
    apply_url: 'https://www.nabard.org/content1.aspx?id=572',
    documents_required: 'Aadhaar Card, Land Records, Passport Photo, Bank Account',
    benefits: 'Revolving credit up to Rs 3 lakh at subsidized interest rate of 7% (effective 4% with subvention)',
    language: 'English, Hindi',
  },
  {
    id: 13,
    name: 'Pradhan Mantri Ujjwala Yojana (PMUY)',
    description: 'Provides LPG connections to women from below-poverty-line (BPL) households. Aims to replace unclean cooking fuels with LPG to reduce health hazards.',
    category: 'Women Empowerment',
    state: 'National',
    eligibility_age_min: 18,
    eligibility_age_max: 999,
    eligibility_income_max: 100000,
    eligibility_gender: 'Female',
    eligibility_caste: 'Any',
    apply_url: 'https://www.pmujjwalayojana.com/',
    documents_required: 'Aadhaar Card, BPL Ration Card, Bank Account',
    benefits: 'Free LPG connection, subsidy on first refill, Rs 1,600 financial support for connection',
    language: 'English, Hindi',
  },
  {
    id: 14,
    name: 'PM SVANidhi (PM Street Vendor AtmaNirbhar Nidhi)',
    description: 'Micro-credit facility for street vendors to resume livelihoods affected by COVID-19. Provides collateral-free working capital loans.',
    category: 'Employment',
    state: 'National',
    eligibility_age_min: 18,
    eligibility_age_max: 999,
    eligibility_income_max: 99999999,
    eligibility_gender: 'Any',
    eligibility_caste: 'Any',
    apply_url: 'https://pmsvanidhi.mohua.gov.in/',
    documents_required: 'Aadhaar Card, Street Vending Certificate or LoR, Bank Account',
    benefits: 'Collateral-free loans: Rs 10,000 (1st), Rs 20,000 (2nd), Rs 50,000 (3rd) with interest subsidy',
    language: 'English, Hindi',
  },
  {
    id: 15,
    name: 'Rashtriya Swasthya Bima Yojana (RSBY)',
    description: 'Health insurance scheme for BPL families providing smart card-based cashless treatment at empaneled hospitals.',
    category: 'Health',
    state: 'National',
    eligibility_age_min: 0,
    eligibility_age_max: 999,
    eligibility_income_max: 60000,
    eligibility_gender: 'Any',
    eligibility_caste: 'Any',
    apply_url: 'https://www.rsby.gov.in/',
    documents_required: 'BPL Card, Aadhaar Card, Family Photo',
    benefits: 'Rs 30,000 annual health insurance per family, smart card for cashless treatment',
    language: 'English, Hindi',
  },
  {
    id: 16,
    name: 'YSR Rythu Bharosa (Andhra Pradesh)',
    description: 'Andhra Pradesh government scheme providing financial assistance of Rs 13,500 per year to tenant farmers and land owner farmers for investment support.',
    category: 'Agriculture',
    state: 'Andhra Pradesh',
    eligibility_age_min: 18,
    eligibility_age_max: 999,
    eligibility_income_max: 99999999,
    eligibility_gender: 'Any',
    eligibility_caste: 'Any',
    apply_url: 'https://ysrrythu.ap.gov.in/',
    documents_required: 'Aadhaar Card, Land Records, Bank Account',
    benefits: 'Rs 13,500 per year financial assistance for agricultural investment',
    language: 'English, Telugu',
  },
  {
    id: 17,
    name: 'Telangana Rythu Bandhu',
    description: 'Telangana government investment support scheme providing Rs 10,000 per acre per season to all farmers for purchase of inputs like seeds, fertilizers, and pesticides.',
    category: 'Agriculture',
    state: 'Telangana',
    eligibility_age_min: 18,
    eligibility_age_max: 999,
    eligibility_income_max: 99999999,
    eligibility_gender: 'Any',
    eligibility_caste: 'Any',
    apply_url: 'https://rythu.telangana.gov.in/',
    documents_required: 'Pahani (land records), Aadhaar Card, Bank Account',
    benefits: 'Rs 10,000 per acre per season (Rabi and Kharif) for agricultural inputs',
    language: 'English, Telugu',
  },
  {
    id: 18,
    name: 'Post Matric Scholarship for SC Students',
    description: 'Central sector scholarship for Scheduled Caste students studying at post-matric level. Covers maintenance allowance, study tour charges, and thesis/dissertation charges.',
    category: 'Education',
    state: 'National',
    eligibility_age_min: 15,
    eligibility_age_max: 35,
    eligibility_income_max: 250000,
    eligibility_gender: 'Any',
    eligibility_caste: 'SC',
    apply_url: 'https://scholarships.gov.in/',
    documents_required: 'Aadhaar Card, Caste Certificate, Income Certificate, Mark Sheets, Bank Account',
    benefits: 'Maintenance allowance Rs 230–1,200 per month + fees reimbursement based on course level',
    language: 'English, Hindi, Telugu',
  },
];

const ws = XLSX.utils.json_to_sheet(schemes);
const wb = XLSX.utils.book_new();
XLSX.utils.book_append_sheet(wb, ws, 'Schemes');

const outPath = path.join(__dirname, '../server/data/schemes.xlsx');
XLSX.writeFile(wb, outPath);
console.log(`✅ schemes.xlsx created at ${outPath} with ${schemes.length} schemes`);
